### ISSUE TITLE
Exception when opening the world map mid-game

### ISSUE THREAD

**Issue by philippeop** [neitsa/PrepareLanding#31]
Rimworld B19
I'm getting an error every time I open the map during a game. It happens each time, not just once.
I imagine there is no PrepareLanding instance since there is no landing to prepare.

> Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
>   at PrepareLanding.Defs.MainButtonWorkerToggleWorld.Activate () [0x00000] in <filename unknown>:0 
>   at RimWorld.MainButtonWorker.InterfaceTryActivate () [0x00000] in <filename unknown>:0 
>   at RimWorld.MainButtonWorker.DoButton (Rect rect) [0x00000] in <filename unknown>:0 
>   at RimWorld.MainButtonsRoot.DoButtons () [0x00000] in <filename unknown>:0 
>   at RimWorld.MainButtonsRoot.MainButtonsOnGUI () [0x00000] in <filename unknown>:0 
>   at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00000] in <filename unknown>:0 
>   at Verse.Root.OnGUI () [0x00000] in <filename unknown>:0

**Comment by neitsa** [comment]
@philippeop : any news on that bug? I'm gonna release the version for 1.0 soon. Thanks!

**Comment by philippeop** [comment]
I believe moving it up fixed the issue. Not having it anymore.
Only mods I could think of conflicting with this would be Faction Control.
