### ISSUE TITLE
Total Rainfall limits too low for wet worlds

### ISSUE THREAD

**Issue by serenewaffles** [neitsa/PrepareLanding#33]
When generating a wet world (i.e. with the "Overall rainfall" slider toward High), it is possible to generate tiles that receive more than 5000mm of rainfall. Because the rainfall filter accepts a maximum value of 5000mm, tiles with more than 5000mm of rainfall cannot be included in results using the rainfall filter.

Steps to reproduce:
1) Generate world with "Overall rainfall" all the way to high
2) Try to filter for a tile with >5000mm rainfall per year

I've also attached a screenshot of the Rainfall section of a World Info tab showing maximum rainfall for the world greater than 5000mm.
![image](https://user-images.githubusercontent.com/775693/46628665-47d53000-cb0c-11e8-9192-1777845f6e96.png)

**Comment by neitsa** [comment]
OMG! Nice catch @serenewaffles ! Thank you for your bug report. I'm going to fix this for the Rimworld 1.0 stable.

**Comment by serenewaffles** [comment]
I managed to generate a world with even more rainfall. 6774mm/year, to be exact.
![image](https://user-images.githubusercontent.com/775693/47171978-2a585100-d2d8-11e8-9602-326a29c735cd.png)
