### ISSUE TITLE
Not Compatible With Rimworld 1.1

### ISSUE THREAD

**Issue by WallabyKingdom** [neitsa/PrepareLanding#35]
The mod is incompatible with Rimworld 1.1. Starting the latest 1.1 version of the game with PrepareLanding active in my mod list resulted in this error message:

> **Recovered from incompatible or corrupted mod errors**
It seems that some of the active mods were causing errors.
They were incompatible with each other, designed for a different version of Rimworld, or corrupted.
All mods have been disabled and can be activated again in the mods dialog.

Starting the game with only HugsLib 1.1 and PrepareLanding active (after the game's own Core and Royalty files) resulted in the same message as the previous try.

I also tried to start the game with just PrepareLanding and no HugsLib and received the following messages in the Debug log:
> RimWorld 1.1.2558 rev1000
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

>ReflectionTypeLoadException getting types in assembly PrepareLanding: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Verse.ModAssemblyHandler.AssemblyIsUsable (System.Reflection.Assembly asm) [0x00000] in <33b99ab6cf5748ec8fe371b3321b9db6>:0 

>Loader exceptions:
   => System.TypeLoadException: Could not resolve type with token 0100003a (from typeref, class/assembly HugsLib.ModBase, HugsLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

>Verse.Log:Error(String, Boolean)
Verse.ModAssemblyHandler:AssemblyIsUsable(Assembly)
Verse.ModAssemblyHandler:ReloadAll()
Verse.ModContentPack:ReloadContent()
Verse.LoadedModManager:LoadModContent()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

>Could not find a type named PrepareLanding.Defs.MainButtonWorkerToggleWorld
Verse.Log:Error(String, Boolean)
Verse.ParseHelper:ParseType(String)
Verse.ParseHelper:FromString(String)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DefFromNode(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

I tried to generate a world with the mod still active anyway. There were no additional options like specific world size percentages in the Create world page. Clicking "Generate" with the standard settings and a random seed gave me a loading screen but sent me back to the Create world page when finished loading. I tried to click back to get to the main menu but after clicking back on the Choose AI storyteller page I was sent to a view of the newly generated planet but I could not click anything or find a way to return the main menu and so was forced to Alt + F4 to close the game.

**Comment by neitsa** [comment]
Thank you for your issue. The Fix will be done during this week end (week 10). The PR by #36 by @JonathanTroyer basically gave me what to fix. I also plan to do some minor fixes and add new filter(s) that would match the RW update.
